import tyre_img from "../../public/tyre_img.webp";

export const tyreData = [
    {
        logo: tyre_img,
        brandName: 'Apollo',
        model: 'AMAZER 4G LIFE',
        size: '145/80 R12',
        price: '3,136',
        reviews: { rating: 4, count: 321 },
        warranty: '5 Year Warranty',
        type: 'Tube Type',
        availability: 'Offer available',
    },
    {
        logo: tyre_img,
        brandName: 'Apollo',
        model: 'AMAZER 4G LIFE',
        size: '145/80 R13',
        price: '3,562',
        reviews: { rating: 4, count: 321 },
        warranty: '5 Year Warranty',
        type: 'Tubeless',
        availability: 'Offer available',
    },
    {
        logo: tyre_img,
        brandName: 'MRF',
        model: 'ZVT',
        size: '165/65 R14',
        price: '4,500',
        reviews: { rating: 5, count: 210 },
        warranty: '5 Year Warranty',
        type: 'Tubeless',
        availability: 'In Stock',
    },
    {
        logo: tyre_img,
        brandName: 'MRF',
        model: 'Wanderer',
        size: '195/65 R15',
        price: '5,800',
        reviews: { rating: 4, count: 150 },
        warranty: '5 Year Warranty',
        type: 'Tubeless',
        availability: 'In Stock',
    },
    {
        logo: tyre_img,
        brandName: 'Bridgestone',
        model: 'Dueler H/L',
        size: '215/60 R16',
        price: '7,200',
        reviews: { rating: 4, count: 89 },
        warranty: '5 Year Warranty',
        type: 'Tubeless',
        availability: 'Pre-order',
    },
    {
        logo: tyre_img,
        brandName: 'Bridgestone',
        model: 'Turanza T001',
        size: '225/55 R17',
        price: '8,000',
        reviews: { rating: 5, count: 123 },
        warranty: '5 Year Warranty',
        type: 'Tubeless',
        availability: 'In Stock',
    },
    {
        logo: tyre_img,
        brandName: 'CEAT',
        model: 'Secura Drive',
        size: '175/70 R13',
        price: '4,000',
        reviews: { rating: 4, count: 190 },
        warranty: '5 Year Warranty',
        type: 'Tubeless',
        availability: 'Offer available',
    },
    {
        logo: tyre_img,
        brandName: 'CEAT',
        model: 'Czar A/T',
        size: '265/70 R15',
        price: '6,500',
        reviews: { rating: 4, count: 75 },
        warranty: '5 Year Warranty',
        type: 'Tubeless',
        availability: 'In Stock',
    },
    {
        logo: tyre_img,
        brandName: 'CST',
        model: 'CST 3000',
        size: '155/70 R13',
        price: '3,800',
        reviews: { rating: 3, count: 210 },
        warranty: '5 Year Warranty',
        type: 'Tube Type',
        availability: 'Offer available',
    },
    {
        logo: tyre_img,
        brandName: 'CST',
        model: 'MAJOR',
        size: '185/60 R14',
        price: '5,000',
        reviews: { rating: 4, count: 140 },
        warranty: '5 Year Warranty',
        type: 'Tubeless',
        availability: 'In Stock',
    },
    {
        logo: tyre_img,
        brandName: 'Dunlop',
        model: 'SP Sport',
        size: '195/55 R16',
        price: '6,200',
        reviews: { rating: 5, count: 180 },
        warranty: '5 Year Warranty',
        type: 'Tubeless',
        availability: 'Pre-order',
    },
    {
        logo: tyre_img,
        brandName: 'Dunlop',
        model: 'Grandtrek AT3',
        size: '235/75 R15',
        price: '7,000',
        reviews: { rating: 4, count: 100 },
        warranty: '5 Year Warranty',
        type: 'Tubeless',
        availability: 'In Stock',
    },
    {
        logo: tyre_img,
        brandName: 'Yokohama',
        model: 'Geolandar AT G015',
        size: '265/60 R18',
        price: '8,500',
        reviews: { rating: 5, count: 95 },
        warranty: '5 Year Warranty',
        type: 'Tubeless',
        availability: 'Pre-order',
    },
    {
        logo: tyre_img,
        brandName: 'Yokohama',
        model: 'Advan Sport V105',
        size: '245/45 R18',
        price: '9,200',
        reviews: { rating: 5, count: 80 },
        warranty: '5 Year Warranty',
        type: 'Tubeless',
        availability: 'In Stock',
    },
    {
        logo: tyre_img,
        brandName: 'Bridgestone',
        model: 'Turanza T005',
        size: '185/65 R15',
        price: '5,499',
        reviews: { rating: 4.5, count: 210 },
        warranty: '4 Year Warranty',
        type: 'Tubeless',
        availability: 'In Stock',
    },
    {
        logo: tyre_img,
        brandName: 'Michelin',
        model: 'Primacy 4',
        size: '195/55 R16',
        price: '6,350',
        reviews: { rating: 4.8, count: 150 },
        warranty: '6 Year Warranty',
        type: 'Tubeless',
        availability: 'Out of Stock',
    },
    {
        logo: tyre_img,
        brandName: 'Goodyear',
        model: 'Eagle F1',
        size: '205/60 R16',
        price: '5,799',
        reviews: { rating: 4.2, count: 275 },
        warranty: '5 Year Warranty',
        type: 'Tubeless',
        availability: 'Offer available',
    },
    {
        logo: tyre_img,
        brandName: 'Continental',
        model: 'ContiSportContact 5',
        size: '215/55 R17',
        price: '7,200',
        reviews: { rating: 4.6, count: 340 },
        warranty: '4 Year Warranty',
        type: 'Tubeless',
        availability: 'In Stock',
    },
    {
        logo: tyre_img,
        brandName: 'Pirelli',
        model: 'Cinturato P7',
        size: '225/50 R17',
        price: '6,000',
        reviews: { rating: 4.3, count: 190 },
        warranty: '5 Year Warranty',
        type: 'Tubeless',
        availability: 'Offer available',
    },
    {
        logo: tyre_img,
        brandName: 'Hankook',
        model: 'Ventus V12 EVO2',
        size: '235/45 R18',
        price: '7,800',
        reviews: { rating: 4.4, count: 130 },
        warranty: '4 Year Warranty',
        type: 'Tubeless',
        availability: 'In Stock',
    },
    {
        logo: tyre_img,
        brandName: 'Yokohama',
        model: 'ADVAN Sport V105',
        size: '245/40 R19',
        price: '8,500',
        reviews: { rating: 4.7, count: 165 },
        warranty: '4 Year Warranty',
        type: 'Tubeless',
        availability: 'In Stock',
    },
    {
        logo: tyre_img,
        brandName: 'Dunlop',
        model: 'SP Sport Maxx',
        size: '255/35 R19',
        price: '9,200',
        reviews: { rating: 4.5, count: 185 },
        warranty: '5 Year Warranty',
        type: 'Tubeless',
        availability: 'Offer available',
    },
    {
        logo: tyre_img,
        brandName: 'Falken',
        model: 'Azenis FK510',
        size: '265/35 R20',
        price: '10,000',
        reviews: { rating: 4.6, count: 120 },
        warranty: '4 Year Warranty',
        type: 'Tubeless',
        availability: 'In Stock',
    },
    {
        logo: tyre_img,
        brandName: 'Nexen',
        model: 'N Fera Sport',
        size: '275/30 R20',
        price: '11,000',
        reviews: { rating: 4.3, count: 140 },
        warranty: '5 Year Warranty',
        type: 'Tubeless',
        availability: 'Out of Stock',
    },
    {
        logo: tyre_img,
        brandName: 'Toyo',
        model: 'Proxes Sport',
        size: '285/30 R21',
        price: '12,500',
        reviews: { rating: 4.8, count: 110 },
        warranty: '4 Year Warranty',
        type: 'Tubeless',
        availability: 'Offer available',
    },
];
